export const PartBreakType = {
  UNBREAKABLE: 0,
  BREAK: 1,
  CUT: 2,
  BLUNT_ONLY: 3,
} as const;

export const ElementType = {
  NO_ELEMENT: 0,
  FIRE: 1,
  WATER: 2,
  THUNDER: 3,
  ICE: 4,
  DRAGON: 5,
  POISON: 6,
  PARALYSIS: 7,
  SLEEP: 8,
  BLAST: 9,
} as const;

export const WeaponType2 = {
  WEAPON_TYPE2_UNKNOWN: 0,
  WEAPON_TYPE2_GREAT_SWORD: 1,
  WEAPON_TYPE2_SWORD_SHIELD: 2,
  WEAPON_TYPE2_DUAL_BLADES: 3,
  WEAPON_TYPE2_LONG_SWORD: 4,
  WEAPON_TYPE2_HAMMER: 5,
  WEAPON_TYPE2_HUNTING_HORN: 6,
  WEAPON_TYPE2_LANCE: 7,
  WEAPON_TYPE2_GUNLANCE: 8,
  WEAPON_TYPE2_SWITCH_AXE: 9,
  WEAPON_TYPE2_CHARGE_BLADE: 10,
  WEAPON_TYPE2_INSECT_GLAIVE: 11,
  WEAPON_TYPE2_BOW: 12,
  WEAPON_TYPE2_HEAVY_BOWGUN: 13,
  WEAPON_TYPE2_LIGHT_BOWGUN: 14,
} as const;
